platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

target 'MacroCosm' do
  
  pod 'SwiftLint'
  pod 'R.swift'
  pod 'JGProgressHUD'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'SwipeableTabBarController', '~> 3.2.1'
  pod 'LocationPicker'

#  Exclude DEPLOYMENT_TARGET warnings
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

  target 'MacroCosmTests' do
      inherit! :search_paths
  end
end
